# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_basic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#1.0.0v

from PyQt5 import QtCore, QtGui, QtWidgets
from Ms_aut import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("SenderFibem")
        MainWindow.resize(820, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Qframe = QtWidgets.QFrame(self.centralwidget)
        self.Qframe.setEnabled(True)
        self.Qframe.setAutoFillBackground(False)
        self.Qframe.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.932, y1:1, x2:0.0395455, y2:0.017, stop:0.284091 rgba(47, 47, 47, 255), stop:1 rgba(70, 70, 70, 255))")
        self.Qframe.setFrameShape(QtWidgets.QFrame.Panel)
        self.Qframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Qframe.setObjectName("Qframe")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Qframe)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Barrasuperior = QtWidgets.QFrame(self.Qframe)
        self.Barrasuperior.setEnabled(True)
        self.Barrasuperior.setStyleSheet("QToolButton{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 37, 255), stop:0.590909 rgba(244, 198, 0, 255), stop:1 rgba(255, 233, 70, 255));\n"
"\n"
"border: 1px solid black;\n"
"border-radius: 10px; \n"
"}\n"
"\n"
"QToolButton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0.989, y1:1, x2:0.00545455, y2:0.023, stop:0 rgba(255, 194, 0, 233), stop:0.5 rgba(255, 240, 39, 233), stop:0.869318 rgba(255, 226, 0, 255))\n"
"}")
        self.Barrasuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Barrasuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Barrasuperior.setObjectName("Barrasuperior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Barrasuperior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Excelexample = QtWidgets.QToolButton(self.Barrasuperior)
        self.Excelexample.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Excelexample.setFont(font)
        self.Excelexample.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Excelexample.setStyleSheet("")
        self.Excelexample.setIconSize(QtCore.QSize(105, 26))
        self.Excelexample.setObjectName("Excelexample")
        self.horizontalLayout_2.addWidget(self.Excelexample)
        self.ExcelFile = QtWidgets.QToolButton(self.Barrasuperior)
        self.ExcelFile.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ExcelFile.setFont(font)
        self.ExcelFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ExcelFile.setObjectName("ExcelFile")
        self.horizontalLayout_2.addWidget(self.ExcelFile)
        self.Filebuton = QtWidgets.QToolButton(self.Barrasuperior)
        self.Filebuton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Filebuton.setFont(font)
        self.Filebuton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Filebuton.setObjectName("Filebuton")
        self.horizontalLayout_2.addWidget(self.Filebuton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(2, 80)
        self.verticalLayout.addWidget(self.Barrasuperior)
        self.Contenedor = QtWidgets.QFrame(self.Qframe)
        self.Contenedor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Contenedor.sizePolicy().hasHeightForWidth())
        self.Contenedor.setSizePolicy(sizePolicy)
        self.Contenedor.setMinimumSize(QtCore.QSize(0, 0))
        self.Contenedor.setMaximumSize(QtCore.QSize(16777215, 600))
        self.Contenedor.setBaseSize(QtCore.QSize(0, 167))
        self.Contenedor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Contenedor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Contenedor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Contenedor.setToolTipDuration(-1)
        self.Contenedor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Contenedor.setStyleSheet("QToolButton{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 37, 255), stop:0.590909 rgba(244, 198, 0, 255), stop:1 rgba(255, 233, 70, 255));\n"
"\n"
"border: 1px solid black;\n"
"border-radius: 10px; \n"
"}\n"
"\n"
"QToolButton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0.989, y1:1, x2:0.00545455, y2:0.023, stop:0 rgba(255, 194, 0, 233), stop:0.5 rgba(255, 240, 39, 233), stop:0.869318 rgba(255, 226, 0, 255))\n"
"}")
        self.Contenedor.setFrameShape(QtWidgets.QFrame.Box)
        self.Contenedor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Contenedor.setObjectName("Contenedor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Contenedor)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Mensaje = QtWidgets.QTextEdit(self.Contenedor)
        self.Mensaje.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"\n"
"border: 1px solid black;\n"
"\n"
"border-radius: 4px; ")
        self.Mensaje.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Mensaje.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Mensaje.setObjectName("Mensaje")
        self.verticalLayout_3.addWidget(self.Mensaje)
        self.Send = QtWidgets.QToolButton(self.Contenedor)
        self.Send.setMaximumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Send.setFont(font)
        self.Send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Send.setObjectName("Send")
        self.verticalLayout_3.addWidget(self.Send)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.Contenedor)
        self.verticalLayout_2.addWidget(self.Qframe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSeleciona_un_archivo = QtWidgets.QAction(MainWindow)
        self.actionSeleciona_un_archivo.setObjectName("actionSeleciona_un_archivo")
        self.actionSeleciona_tu_Excel = QtWidgets.QAction(MainWindow)
        self.actionSeleciona_tu_Excel.setObjectName("actionSeleciona_tu_Excel")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Excelexample.setText(_translate("MainWindow", "Descargar plantilla de  excel"))
        self.ExcelFile.setText(_translate("MainWindow", "Seleciona tu Excel"))
        self.Filebuton.setText(_translate("MainWindow", "Seleciona tu archivo"))
        self.Mensaje.setDocumentTitle(_translate("MainWindow", "Escribe tu mensaje"))
        self.Mensaje.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>Escribe tu mensaje</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Send.setText(_translate("MainWindow", "SEND"))
        self.actionSeleciona_un_archivo.setText(_translate("MainWindow", "Seleciona un archivo"))
        self.actionSeleciona_tu_Excel.setText(_translate("MainWindow", "Seleciona tu Excel"))

        # Logica
        self.Excelexample.clicked.connect(downexamp)
        self.ExcelFile.clicked.connect(select_file)
        self.Filebuton.clicked.connect(img_file)
        self.Send.clicked.connect(lambda:send_message(self.Mensaje))
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
